#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^alumnos/$','konecta2profesor.views.alumnos'),
    url(r'^clases_profesor/$','konecta2profesor.views.clases_profesor'),
    url(r'^registrar_ejercicio/$','konecta2profesor.views.registrar_ejercicio'),
    url(r'^enviar_ejercicio_individual/$','konecta2profesor.views.enviar_ejercicio_individual'),
    url(r'^enviar_ejercicio_todos/$','konecta2profesor.views.enviar_ejercicio_todos'),
    url(r'^informacion_usuario/$','konecta2profesor.views.informacion_usuario'),
    url(r'^materias_ejercicios/$','konecta2profesor.views.materias_ejercicios'),
    url(r'^cursos_ejercicios/$','konecta2profesor.views.cursos_ejercicios'),
    url(r'^ejercicios_totales/$','konecta2profesor.views.ejercicios_totales'),
    url(r'^ejercicios_totales_android/$','konecta2profesor.views.ejercicios_totales_android'),
    url(r'^dificultad_ejercicios/$','konecta2profesor.views.dificultad_ejercicios'),
    url(r'^crear_curso/$','konecta2profesor.views.crear_curso'),
    url(r'^crear_materia/$','konecta2profesor.views.crear_materia'),
    url(r'^crear_tema/$','konecta2profesor.views.crear_tema'),
    url(r'^temas_ejercicios/$','konecta2profesor.views.temas_ejercicios'),
    url(r'^favorito_crear/$','konecta2profesor.views.favorito_crear'),
    url(r'^favorito_borrar/$','konecta2profesor.views.favorito_borrar'),
    url(r'^detalles_ejercicio_java/$','konecta2profesor.views.detalles_ejercicio_java'),
    url(r'^eliminar_ejercicio/$','konecta2profesor.views.eliminar_ejercicio'),
    url(r'^crear_clase/$','konecta2profesor.views.crear_clase'),
    url(r'^corregir_ejercicio/$','konecta2profesor.views.corregir_ejercicio'),
    url(r'^ver_corregir_ejercicio/$','konecta2profesor.views.ver_corregir_ejercicio'),
    url(r'^eliminar_corregir/$','konecta2profesor.views.eliminar_corregir'),
    url(r'^modificar_ejercicio/$','konecta2profesor.views.modificar_ejercicio'),
    url(r'^detalles_usuario/$','konecta2profesor.views.detalles_usuario'),
    url(r'^guardar_incidencia/$','konecta2profesor.views.guardar_incidencia'),
    url(r'^guardar_observacion/$','konecta2profesor.views.guardar_observacion'),
    url(r'^ver_observacion/$','konecta2profesor.views.ver_observacion'),
    url(r'^ver_incidencia/$','konecta2profesor.views.ver_incidencia'),
    url(r'^materias_totales_java/$','konecta2profesor.views.materias_totales_java'),
    url(r'^detalles_ejercicio_profesor/$','konecta2profesor.views.detalles_ejercicio_profesor'),
    url(r'^ver_imagen_corregir/$','konecta2profesor.views.ver_imagen_corregir'),
    url(r'^reenviar_ejercicio/$','konecta2profesor.views.reenviar_ejercicio'),   
    
    url(r'^ejercicios_normales/$','konecta2profesor.views.ejercicios_normales'),
    url(r'^ejercicios_clase/$','konecta2profesor.views.ejercicios_clase'),
    url(r'^controles/$','konecta2profesor.views.controles'),
    url(r'^examenes/$','konecta2profesor.views.examenes'),
    url(r'^globales/$','konecta2profesor.views.globales'),
    url(r'^corregir/$','konecta2profesor.views.corregir'),
    
    
    url(r'^get_elementos/$','konecta2profesor.busquedas.get_elementos'),
    url(r'^busqueda_filtros/$','konecta2profesor.busquedas.busqueda_filtros'),
    url(r'^busqueda/$','konecta2profesor.busquedas.search'),
)